
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 17;
  public static final int Begin = 2;
  public static final int OpSuma = 20;
  public static final int End = 3;
  public static final int Until = 11;
  public static final int Coma = 28;
  public static final int Conststr = 32;
  public static final int Repeat = 34;
  public static final int If = 6;
  public static final int ParentesisAbierto = 26;
  public static final int Else = 9;
  public static final int Variable = 30;
  public static final int Read = 14;
  public static final int StringPattern = 37;
  public static final int AsignacionIgual = 24;
  public static final int Then = 10;
  public static final int FinalInstruccion = 25;
  public static final int Punto = 29;
  public static final int While = 12;
  public static final int To = 7;
  public static final int For = 4;
  public static final int EOF = 0;
  public static final int Not = 16;
  public static final int Function = 5;
  public static final int And = 18;
  public static final int error = 1;
  public static final int AsignacionTipo = 23;
  public static final int AsignacionVariable = 22;
  public static final int Tipo = 15;
  public static final int Do = 8;
  public static final int OpMult = 21;
  public static final int OpRel = 19;
  public static final int Constchar = 31;
  public static final int ParentesisCerrado = 27;
  public static final int Write = 13;
  public static final int Numero = 36;
  public static final int Program = 33;
  public static final int Procedure = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Begin",
  "End",
  "For",
  "Function",
  "If",
  "To",
  "Do",
  "Else",
  "Then",
  "Until",
  "While",
  "Write",
  "Read",
  "Tipo",
  "Not",
  "Or",
  "And",
  "OpRel",
  "OpSuma",
  "OpMult",
  "AsignacionVariable",
  "AsignacionTipo",
  "AsignacionIgual",
  "FinalInstruccion",
  "ParentesisAbierto",
  "ParentesisCerrado",
  "Coma",
  "Punto",
  "Variable",
  "Constchar",
  "Conststr",
  "Program",
  "Repeat",
  "Procedure",
  "Numero",
  "StringPattern"
  };
}

